// <auto-generated />
using System;
using FlightFinderAPI.Services.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlightFinderAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230308085951_test1")]
    partial class test1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.14");

            modelBuilder.Entity("FlightFinderAPI.Domain.Booking", b =>
                {
                    b.Property<Guid>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FlightId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("PriceToPay")
                        .HasColumnType("REAL");

                    b.Property<string>("RouteId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("BookingId");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            BookingId = new Guid("e910476f-3439-4728-a0d2-76bf92576740"),
                            Currency = "SEK",
                            FlightId = "6e4b483d",
                            PriceToPay = 140.39f,
                            RouteId = "0e2f3647"
                        });
                });

            modelBuilder.Entity("FlightFinderAPI.Domain.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.HasIndex("BookingId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("bf182d5d-8489-48e6-8e87-dd2d90a7fbb6"),
                            BookingId = new Guid("e910476f-3439-4728-a0d2-76bf92576740"),
                            Name = "maxi",
                            Password = "maxi",
                            UserName = "maxi"
                        });
                });

            modelBuilder.Entity("FlightFinderAPI.Domain.User", b =>
                {
                    b.HasOne("FlightFinderAPI.Domain.Booking", "BookedFlights")
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BookedFlights");
                });
#pragma warning restore 612, 618
        }
    }
}
